# Generated by Django 4.0.3 on 2022-05-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_user_role_code_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
